// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	dto "system-discovery/internal/dto"

	mock "github.com/stretchr/testify/mock"
)

// ICounterService is an autogenerated mock type for the ICounterService type
type ICounterService struct {
	mock.Mock
}

// GetOperations provides a mock function with given fields: sinceStr
func (_m *ICounterService) GetOperations(sinceStr string) []dto.IncrementRequest {
	ret := _m.Called(sinceStr)

	if len(ret) == 0 {
		panic("no return value specified for GetOperations")
	}

	var r0 []dto.IncrementRequest
	if rf, ok := ret.Get(0).(func(string) []dto.IncrementRequest); ok {
		r0 = rf(sinceStr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.IncrementRequest)
		}
	}

	return r0
}

// GetValue provides a mock function with no fields
func (_m *ICounterService) GetValue() map[string]int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetValue")
	}

	var r0 map[string]int
	if rf, ok := ret.Get(0).(func() map[string]int); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int)
		}
	}

	return r0
}

// Increment provides a mock function with given fields: ctx
func (_m *ICounterService) Increment(ctx context.Context) string {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Increment")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Replicate provides a mock function with given fields: ctx, req
func (_m *ICounterService) Replicate(ctx context.Context, req dto.IncrementRequest) string {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Replicate")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, dto.IncrementRequest) string); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewICounterService creates a new instance of ICounterService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewICounterService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ICounterService {
	mock := &ICounterService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
