// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	dto "system-discovery/internal/dto"

	mock "github.com/stretchr/testify/mock"
)

// IDiscoveryService is an autogenerated mock type for the IDiscoveryService type
type IDiscoveryService struct {
	mock.Mock
}

// GetAllPeers provides a mock function with given fields: ctx
func (_m *IDiscoveryService) GetAllPeers(ctx context.Context) []string {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllPeers")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// SyncAndStorePeers provides a mock function with given fields: ctx, request
func (_m *IDiscoveryService) SyncAndStorePeers(ctx context.Context, request dto.SyncPeersRequest) []string {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for SyncAndStorePeers")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func(context.Context, dto.SyncPeersRequest) []string); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// NewIDiscoveryService creates a new instance of IDiscoveryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIDiscoveryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IDiscoveryService {
	mock := &IDiscoveryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
