// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	dto "system-discovery/internal/dto"

	mock "github.com/stretchr/testify/mock"
)

// IRegistrationService is an autogenerated mock type for the IRegistrationService type
type IRegistrationService struct {
	mock.Mock
}

// DeRegister provides a mock function with given fields: _a0, peer
func (_m *IRegistrationService) DeRegister(_a0 context.Context, peer string) {
	_m.Called(_a0, peer)
}

// Register provides a mock function with given fields: _a0, request
func (_m *IRegistrationService) Register(_a0 context.Context, request dto.RegisterRequest) {
	_m.Called(_a0, request)
}

// NewIRegistrationService creates a new instance of IRegistrationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIRegistrationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IRegistrationService {
	mock := &IRegistrationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
