// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// IServiceCall is an autogenerated mock type for the IServiceCall type
type IServiceCall struct {
	mock.Mock
}

// Get provides a mock function with given fields: ctx, endpoint, headers, timeout
func (_m *IServiceCall) Get(ctx context.Context, endpoint string, headers map[string]string, timeout ...time.Duration) ([]byte, int, error) {
	_va := make([]interface{}, len(timeout))
	for _i := range timeout {
		_va[_i] = timeout[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, endpoint, headers)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []byte
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]string, ...time.Duration) ([]byte, int, error)); ok {
		return rf(ctx, endpoint, headers, timeout...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]string, ...time.Duration) []byte); ok {
		r0 = rf(ctx, endpoint, headers, timeout...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, map[string]string, ...time.Duration) int); ok {
		r1 = rf(ctx, endpoint, headers, timeout...)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, map[string]string, ...time.Duration) error); ok {
		r2 = rf(ctx, endpoint, headers, timeout...)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Post provides a mock function with given fields: ctx, endpoint, body, headers, timeout
func (_m *IServiceCall) Post(ctx context.Context, endpoint string, body interface{}, headers map[string]string, timeout ...time.Duration) ([]byte, int, error) {
	_va := make([]interface{}, len(timeout))
	for _i := range timeout {
		_va[_i] = timeout[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, endpoint, body, headers)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Post")
	}

	var r0 []byte
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}, map[string]string, ...time.Duration) ([]byte, int, error)); ok {
		return rf(ctx, endpoint, body, headers, timeout...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}, map[string]string, ...time.Duration) []byte); ok {
		r0 = rf(ctx, endpoint, body, headers, timeout...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, interface{}, map[string]string, ...time.Duration) int); ok {
		r1 = rf(ctx, endpoint, body, headers, timeout...)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, interface{}, map[string]string, ...time.Duration) error); ok {
		r2 = rf(ctx, endpoint, body, headers, timeout...)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewIServiceCall creates a new instance of IServiceCall. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIServiceCall(t interface {
	mock.TestingT
	Cleanup(func())
}) *IServiceCall {
	mock := &IServiceCall{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
