// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ISyncService is an autogenerated mock type for the ISyncService type
type ISyncService struct {
	mock.Mock
}

// StartSync provides a mock function with given fields: ctx
func (_m *ISyncService) StartSync(ctx context.Context) {
	_m.Called(ctx)
}

// NewISyncService creates a new instance of ISyncService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewISyncService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ISyncService {
	mock := &ISyncService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
